import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import "./i18n";
import { initOfflineSync } from "@/lib/offlineQueue";
import { bootApplyUIPrefs } from "@/lib/uiScale";
import { initStatusBarTheme } from "@/lib/statusBarTheme";

bootApplyUIPrefs();
initStatusBarTheme();

// Guard: never register a service worker inside Lovable preview/iframe contexts
const isInIframe = (() => {
  try {
    return window.self !== window.top;
  } catch {
    return true;
  }
})();
const host = window.location.hostname;
const isPreviewHost =
  host.includes("id-preview--") ||
  host.includes("lovableproject.com") ||
  (host.includes("lovable.app") && host.includes("id-preview"));

if (isPreviewHost || isInIframe) {
  // Cleanup any previously registered SW so preview never serves stale content
  if ("serviceWorker" in navigator) {
    navigator.serviceWorker.getRegistrations().then((rs) => rs.forEach((r) => r.unregister()));
  }
} else if ("serviceWorker" in navigator) {
  // Production / installed PWA: register the worker generated by vite-plugin-pwa
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      const AUTO_UPDATE_KEY = "arshnaz_auto_update";
      const isAutoUpdate = () => {
        try {
          return localStorage.getItem(AUTO_UPDATE_KEY) !== "false";
        } catch {
          return true;
        }
      };

      let autoUpdateTimer: number | undefined;
      let registrationRef: ServiceWorkerRegistration | undefined;

      const updateSW = registerSW({
        immediate: true,
        onNeedRefresh() {
          // New version available — surface a toast and let user trigger update.
          (window as unknown as { __applyPwaUpdate?: () => void }).__applyPwaUpdate = () =>
            updateSW(true);
          window.dispatchEvent(new CustomEvent("pwa-update-available"));

          // If auto-update is enabled (default), install after a short grace period.
          if (isAutoUpdate()) {
            window.clearTimeout(autoUpdateTimer);
            autoUpdateTimer = window.setTimeout(() => {
              updateSW(true);
            }, 1500);
          }
        },
        onRegisteredSW(_swUrl, registration) {
          if (registration) {
            registrationRef = registration;
            // Poll for updates every 30s so new publishes are picked up fast
            setInterval(() => {
              registration.update().catch(() => {});
            }, 30 * 1000);
          }
        },
        onRegisterError(error) {
          console.error("SW registration failed:", error);
        },
      });

      // Expose helpers for SettingsView and other UI
      (window as unknown as { __pwaRegistration?: ServiceWorkerRegistration }).__pwaRegistration =
        registrationRef;
      (window as unknown as { __pwaCheckUpdate?: () => Promise<boolean> }).__pwaCheckUpdate =
        async () => {
          const reg = registrationRef || (await navigator.serviceWorker.getRegistration());
          if (!reg) return false;
          const before = reg.waiting || reg.installing;
          let found = false;
          let listener: (() => void) | undefined;
          const promise = new Promise<void>((resolve) => {
            const onFound = () => {
              const after = reg.installing || reg.waiting;
              if (after && after !== before) {
                found = true;
                resolve();
              }
            };
            listener = onFound;
            reg.addEventListener("updatefound", onFound);
            onFound();
            setTimeout(() => resolve(), 5000);
          });
          await Promise.race([
            reg.update().catch(() => {}),
            new Promise<void>((r) => setTimeout(r, 3000)),
          ]);
          await promise;
          if (listener) reg.removeEventListener("updatefound", listener);
          return found;
        };

      // Reload the page once the new SW takes control (after user accepts).
      let refreshing = false;
      navigator.serviceWorker.addEventListener("controllerchange", () => {
        if (refreshing) return;
        refreshing = true;
        window.location.reload();
      });
    })
    .catch((err) => {
      console.error("PWA registration failed:", err);
    });
}

initOfflineSync();

createRoot(document.getElementById("root")!).render(<App />);
